# Generated by Django 5.0.7 on 2024-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0008_alter_user_dob_alter_user_gender_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='latitude',
            field=models.FloatField(default=111.25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
