# Generated by Django 5.0.7 on 2024-08-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0011_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
