# Generated by Django 5.0.7 on 2024-08-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0012_remove_assessment_evaluation_criteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassessment',
            name='answers',
        ),
    ]
