# Generated by Django 5.0.7 on 2024-08-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0014_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('result', models.CharField(default='Not assessed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='selected_choice',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='mental_wellness',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='language',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='language',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='longitude',
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('emotional_wellbeing', 'Emotional Well-being'), ('cognitive_functioning', 'Cognitive Functioning'), ('lifestyle_habits', 'Lifestyle and Habits')], default='emotional_wellbeing', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='BunyanApp.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BunyanApp.assessment'),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BunyanApp.user'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
