# Generated by Django 5.0.7 on 2024-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0005_language_code_alter_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='therapists',
        ),
        migrations.AddField(
            model_name='therapist',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='BunyanApp.specialization'),
        ),
    ]
