# Generated by Django 5.0.7 on 2024-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0006_remove_specialization_therapists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='experience',
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_years',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
