# Generated by Django 5.0.7 on 2024-08-27 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunyanApp', '0008_alter_user_dob_alter_user_gender_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='mental_wellness',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assessment',
            name='evaluation_criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('emotional_wellbeing', 'Emotional Well-being'), ('cognitive_functioning', 'Cognitive Functioning'), ('lifestyle_habits', 'Lifestyle and Habits')], default='emotional_wellbeing', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('result', models.CharField(default='Not assessed', max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BunyanApp.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BunyanApp.user')),
            ],
        ),
    ]
